### ISSUE TITLE
Should have a Readme that describes how to publish

### ISSUE THREAD

**Issue by vt102** [KnoxDevs/knoxdevs.github.io#1]
Should have a Readme that describes how to publish to my own test website before submitting a pull request.

**Comment by alexpawlowski** [comment]
Will add some language to the [Contributing.md](https://github.com/KnoxDevs/knoxdevs.github.io/blob/master/Contributing.md) that address the jekyll setup.

**Comment by alexpawlowski** [comment]
I took a stab at addressing this concern, does this change to the [Contributing Guide](https://github.com/KnoxDevs/knoxdevs.github.io/blob/0c39b8e05ecd9294e7d055f4e1fe3c95595f38ff/Contributing.md) help that, @vt102?

**Comment by alexpawlowski** [comment]
I will reopen this issue if there are further things we should address. Thank you for the much needed suggestion!
