### ISSUE TITLE
Link to KnoxDevs Discord

### ISSUE THREAD

**Issue by wigging** [KnoxDevs/knoxdevs.github.io#27]
Should there be a link to join the KnoxDevs Discord server on the homepage? There is currently only a link to join the Slack group on the KnoxDevs website.

**Comment by gregors** [comment]
@wigging I think that's a great idea.

**Comment by wigging** [comment]
@gregors Ha, I didn't realize you were on the KnoxDevs GitHub. You're everywhere! I'll submit a Pull Request with the Discord link. Although, you could do this yourself if you want.

**Comment by wigging** [comment]
🦗
